### PR TITLE
Fixed swift 3.1 compiler warnings

### PR DESCRIPTION
**Pull request by patricks**

### CODE REVIEW

**Comment by phimage** [comment]
Thanks
I will make some modification

**Comment by wattson12** [comment]
@phimage as these changes aren't in 1.1.1, would it be possible to get a version bump? thanks

**Comment by phimage** [comment]
just a tag?

**Comment by wattson12** [comment]
I'm using cocoapods so ideally a tag + update to the podspec, but can point to a tag as well if there is one

**Comment by phimage** [comment]
so you do not need a tag or podspec push, just use the head version by specifying the git url (or point on specific commit)
I cannot do podspec push, I have no access to a computer for several days

**Comment by wattson12** [comment]
OK no worries, thanks for the quick response (btw I'm happy to submit a PR with podspec changes for when it can be pushed, though would need to know the new version number)

**Pull request merged**
