### PR TITLE
Swift 5

### PR DESCRIPTION
**Pull request by alex-taffe**
Really nothing needed to be changed besides just clicking the button

### CODE REVIEW

**Comment by alex-taffe** [comment]
Travis CI appears not to support swift 5 yet so the build is failing

**Comment by christoff-1992** [comment]
@alex-taffe you can edit the travis config for `osx_image: xcode10` to `osx_image: xcode10.2` I have used it this morning myself in https://github.com/zenangst/Blueprints/pull/102 and it seams to work as expected.

**Comment by phimage** [comment]
Thanks for the PR

I see on travis with this new image that  some option are deprecated for gem

$ gem install xcpretty --no-rdoc --no-ri --no-document --quiet
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-rdoc
The command "gem install xcpretty --no-rdoc --no-ri --no-document --quiet" failed and exited with 1 during .

could you edit your PR and remove --no-rdoc  in travis file  (--no-document make the job)

**Comment by alex-taffe** [comment]
@phimage @christoff-1992 fixed those issues now there’s some DANGER_GITHUB_API_TOKEN missing, not sure what to do with that

**Comment by phimage** [comment]
Old issue that I did not resolve yet
I will check and merge

**Comment by phimage** [comment]
Thank you for the PR
I update main for danger
It seems to work now

I am wondering if I will make a 2.0.0 version by replacing all
`success: OAuthSwiftHTTPRequest.SuccessHandler?, failure: `

by an unique handler with the new integrated Result type

**Comment by alex-taffe** [comment]
@phimage Can you push the updated build to the pods repository?

**Comment by phimage** [comment]
Unfortunately I cannot access to a macOS for one week
Please use the head code by editing your podfile

**Comment by alex-taffe** [comment]
No big deal, just when you have time. Thanks

**Pull request merged**
