### PR TITLE
Create a swift-version file

### PR DESCRIPTION
**Pull request by SMillerDev**
This allows CocoaPods to use a specific swift version

CocoaPods/CocoaPods#5841

### CODE REVIEW

**Comment by phimage** [comment]
must be for swift2.3 branch?

master branch will be swift3.0 after #267

**Comment by SMillerDev** [comment]
Well, it would be useful for all branches to have explicit versions. But this particular one was for 2.3 indeed.

**Comment by SMillerDev** [comment]
I could make PRs for the other branches too if required

**Comment by phimage** [comment]
thanks, I will add instruction to the swift3 PR

**Pull request merged**
